services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: diaryuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: diary_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
