"use client"
import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "~/components/ui/toaster";
import { useThemeStore } from "~/store/themeStore";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const theme = useThemeStore((state) => state.theme);
  const themeText = useThemeStore((state) => state.text);
  return (
    <html lang="ja" className={`${GeistSans.variable}`}>
      <body className={`${themeText}`}>
      <SessionProvider>
        {children}
      </SessionProvider>
      <Toaster />
      </body>
    </html>
  );
}
